name: 'image build'
description: 'we are creating docker image from docker file.'
on:
    push:
        branches: [ master ]
    workflow_dispatch:
        inputs:
            image_name:
                description: 'my-app'
                required: true
                
            tag:
                description: 'latest'
                required: true
            dockerfile:
                description: './Dockerfile'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'checkout code'
              uses: actions/checkout@v3
            - name: Build Docker image
              run: docker build -t my-app:latest .
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: 
               docker/login-action@v3         
          with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
           context: .
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest 
           
    
            

              
              

env:
    IMAGE_NAME: ${{ inputs.image_name }}
    TAG: ${{ inputs.tag }}
    DOCKERFILE: ${{ inputs.dockerfile }}
