name: 'image build'
description: 'we are creating docker image from docker file.'
on:
    push:
        branches: [ master ]
    workflow_dispatch:
        inputs:
            image_name:
                description: 'my-app'
                required: true
                
            tag:
                description: 'latest'
                required: true
            dockerfile:
                description: './Dockerfile'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'checkout code'
              uses: actions/checkout@v3
            - name: Build Docker image
              run: docker build -t $IMAGE_NAME:$TAG -f $DOCKERFILE .
env:
    IMAGE_NAME: ${{ inputs.image_name }}
    TAG: ${{ inputs.tag }}
    DOCKERFILE: ${{ inputs.dockerfile }}
